### ISSUE TITLE
Not able to auto-fill report; No way to proceed to next video

### ISSUE THREAD

**Issue by cciivv** [MACCNYC/no-platform-extension#1]
Steps:
1)install plugin
2) press refresh icon
    -> "8 YouTube videos to report [Start Reporting]" appears
3) press "Start Reporting" button
    -> taken to TWP video on youtube
    -> !!!Expecting report menu to be auto-selected/opened/pre-filled
4) Fill in and Submit report for video
5) Click this extention's icon on toolbar
    -> !!!Expecting new button to lead to next video to be reported

Thought it was because I was using the old youtube style, but latest youtube redesign doesn't work either?

Chrome Version 63.0.3239.84

**Comment by katyannflowergirl** [comment]
I'm having the same issue, I use Google Chrome Version 63.0.3239.108 (Official Build) (64-bit) on Linux (Debian).

**Comment by macctech** [comment]
Hi, we've uploaded a new version with some updates that may have fixed your issues. 

Can you go to your extensions panel in Chrome (chrome://extensions/), find No Platform For Fascism Tool Kit, and look for the version number next to it? If you have the latest, it should say "1.2.0".

![settingspage](https://user-images.githubusercontent.com/33007427/34340270-1c86f8e2-e94f-11e7-895e-fc52aa4a18f9.png)

If not, wait a little while and you should get the update soon. Once you see that you have the latest version try again and let us know if you're still having trouble!

**Comment by cciivv** [comment]
v1.2.2 seems to be working for me :)
