### ISSUE TITLE
Reporting doesn't work on chromium.

### ISSUE THREAD

**Issue by Poomex** [MACCNYC/no-platform-extension#2]
Hi, I would like to help out the reporting, but I've installed the extenson on Chromium (63.0.3239.84) on Ubuntu 16.04 and after pressing "start reporting" I get transferred to the videos in question and nothin else happens. When I click "report" the "more" option opens and nothing else happens. I am using YT in Polish if that makes any difference.

**Comment by Poomex** [comment]
Is this ever going to be fixed? What's the point of creating and advertising such an extension if it doesn't work at all and nobody is working on it?

**Comment by macctech** [comment]
Hey there, sorry for the late reply. Please keep in mind this is a project run by a small handful of volunteers and we're doing our best! 😬 

I haven't been able to look at your specific browser/OS version, but we have fixed a few bugs here are there. Would you mind trying again and letting me know if you're still having issues?
